[package]
name = "rsakey_generator"
version = "0.1.0"
authors = ["盒子<open@wanlei.net>"]
edition = "2021"
description = "RSA Key 生成器"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "0.5"
rand = "0.8.5"
